### ISSUE TITLE
setup.py should include pynauty

### ISSUE THREAD

**Issue by rsln-s** [danlkv/QTensor#22]
I recently found out that pynauty is now on PyPi (https://github.com/michaelRadigan/pynauty-nice/issues/2, https://pypi.org/project/pynauty/), which should simplify the dependencies for the symmetry accelerated methods. I think simply adding it to setup.py [1] should do the trick, but it needs to be tested.

https://github.com/danlkv/QTensor/blob/c122a952e21509b87796c397436667a72b392d2f/setup.py#L17

**Comment by danlkv** [comment]
looks like it works, thanks!
